Add pre- and post-hooks
stac-utils/stac-server pull request #271
Opened 2022-06-07 14:32 UTC by marchuffnagle

This PR adds support for pre- and post-hook lambda functions. If configured, these have the ability to modify (and possibly short-circuit) the incoming request, and also modify the response from stac-server before it is sent to the client.

The details of this change are documented in [README.md](https://github.com/stac-utils/stac-server/blob/pre-and-post-hooks/README.md#pre--and-post-hooks) and [tests/README.md](https://github.com/stac-utils/stac-server/blob/pre-and-post-hooks/tests/README.md#aws-tests).

2022-06-07 19:52 UTC, philvarner commented on README.md
> +If the stac-server is deployed with the `PRE_HOOK` environment variable set to the name of a lambda function, then that function will be called as the pre-hook.
could you add an example of what the value PRE_HOOK and POST_HOOK are set to look like? It's unclear to me just reading this what the "name" of the lambda is.

2022-06-07 19:52 UTC, philvarner commented on README.md
> +If the stac-server is deployed with the `PRE_HOOK` environment variable set to the name of a lambda function, then that function will be called as the pre-hook.
could you add an example of what the value PRE_HOOK and POST_HOOK are set to look like? It's unclear to me just reading this what the "name" of the lambda is.

2022-06-07 19:58 UTC, philvarner commented on CHANGELOG.md
> +- Used map instead of foreach/push in api.js file
Could you add a note in Changed about not compressing the  response and the 6MB limit?

2022-06-07 19:58 UTC, philvarner commented on CHANGELOG.md
> +- Used map instead of foreach/push in api.js file
Could you add a note in Changed about not compressing the  response and the 6MB limit?

2022-06-07 19:58 UTC, philvarner commented on README.md
> +
maybe also add something here about the 6MB limit for the event size

2022-06-07 20:01 UTC, philvarner submitted a review, later dismissed

2022-06-07 20:02 UTC, philvarner requested changes
Few documentation requests.

2022-06-08 15:51 UTC, marchuffnagle commented
> Under what conditions would the responses be compressed?

I _believe_ that API Gateway is configured to compress responses larger than 1 MB. There is a limit of 6MB on the uncompressed response.

2022-06-08 16:03 UTC, philvarner approved these changes

2022-06-08 16:04 UTC, merged